(define (problem problema1)
   (:domain ferma)
   (:objects Vasile boxa1 boxa2 boxa3 boxa-hrana)
   (:init 
        (fermier Vasile)
        (liber Vasile)
        (locatie-fermier boxa-hrana)
        (boxa boxa1)
        (boxa boxa2)
        (boxa boxa3)
        (boxa boxa-hrana)
        (sursahrana boxa-hrana)
        (animal boxa1)
        (animal boxa2)
        (animal boxa3)
        (de-hranit boxa1)
        (de-hranit boxa2)
        (de-hranit boxa3)
 )
   (:goal (and (hranit boxa1)
               (hranit boxa2)
               (hranit boxa3)
               (curatare boxa1)
               (curatare boxa2)
               (curatare boxa3)
               (adapat boxa1)
               (adapat boxa2)
               (adapat boxa3)
               ))
               )
